#CONFIGURACIONES BASICAS
spring.application.name=springsecurity_v4

#CONFIGURACIONES DE SEGURIDAD
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}

#CONFIGURACIONES BBDD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
